version: '3'
services:
  backend:
    build:
      context: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py initdata -all &&
             daphne -b 0.0.0.0 -p 8000 XUEKE.asgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    # ports:
    #   - '8000:8000'
    # 8000 端口仅在内部暴露给其他Docker服务，该端口将不再发布到主机
    expose:
      - 8000
    depends_on:
      - db
      - redis

  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=qiaofinn
      - POSTGRESQL_PASSWORD=liu*963.
      - POSTGRESQL_DATABASE=xueke
    ports:
      - '5432'
    volumes:
      - postgres_data:/bitnami/postgresql

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 28000:80
    depends_on:
      - backend
    # links:
    #   - backend
volumes:
  postgres_data:
  static_volume:
  media_volume: