version: "3.7"

services:
  backend:
    container_name: xk_backend
    build: .
    #    image: ccr.ccs.tencentyun.com/rytd/django
    #    command: gunicorn XUEKE.wsgi:application -w 3 -b 0.0.0.0 -c hooks.py
    #    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 XUEKE.asgi:application"
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
        # daphne -b 0.0.0.0 XUEKE.asgi:application
    #   python manage.py initdata
    volumes:
      #      - ./persistance-logs/:/app/logs/
      #      - .:/app
      #      - 最好将当前项目都进行映射否则更新的文件无法更新到容器中
      - ./.secrets.yaml:/app/.secrets.yaml
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=liu*963.
      - POSTGRESQL_DATABASE=xueke
    volumes:
      - pg_data:/bitnami/postgresql
    ports:
      - '5432'

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 28000:80
  #   depends_on:
  #     - backend
  #   links:
  #     - backend


volumes:
  redis_data:
  pg_data: