# Generated by Django 3.2 on 2022-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='addr',
            field=models.JSONField(verbose_name='消费地址'),
        ),
    ]
